/**
 * MockKybProvider — Phase 1 stub for Know Your Business checks.
 *
 * Returns canned, well-formed credential data for any supplier.
 * The credentialHash is derived from the supplier's registration number so
 * results are deterministic across runs — useful for snapshot tests and
 * for seeding the same supplier repeatedly without duplicate hash conflicts.
 *
 * No external API calls are made.
 */

import type { KybProvider, KybSubject, KybCredential } from '../adapters/kyb';

// Default credential validity: 1 year from now
const DEFAULT_EXPIRY_MS = 365 * 24 * 60 * 60 * 1000;

export class MockKybProvider implements KybProvider {
  async runChecks(subject: KybSubject): Promise<KybCredential> {
    // Deterministic hash: keccak256-like via a simple digest of the key fields.
    // In production this is keccak256 of the full credential bundle.
    // Here we produce a stable 32-byte hex that changes if the registration number changes.
    const hashInput = `${subject.registrationNumber}:${subject.country}:mock-kyb-v1`;
    const credentialHash = await deterministicBytes32(hashInput);

    const now = new Date();
    const expiresAt = new Date(now.getTime() + DEFAULT_EXPIRY_MS);

    return {
      registrationNumber: subject.registrationNumber,
      legalName: subject.legalName,
      registrationCountry: subject.country,
      registrationDate: '2020-03-15', // canned date
      credentialHash,
      issuedAt: now,
      expiresAt,
      rawData: {
        source: 'mock_kyb_provider',
        businessStatus: 'active',
        directors: [
          { name: 'Mock Director', role: 'CEO' },
        ],
        shareholders: [
          { name: 'Mock Holding Co', percentage: 100 },
        ],
        note: 'This is synthetic KYB data generated by MockKybProvider for Phase 1 testing.',
      },
    };
  }
}

/**
 * Produces a deterministic 32-byte hex string from an input string.
 * Uses the Web Crypto API (available in Node.js 18+ and all modern browsers).
 */
async function deterministicBytes32(input: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(input);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return '0x' + hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}
